#!/usr/bin/env python3

# Copyright (C) 2023 Caian Benedicto <caian@ggaunicamp.com>
#
# This software is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import sys
from subprocess import run, PIPE

dc = ','.join(sys.argv[1:])

if dc == '':
    raise Exception('Missing dc argument!')

print('# LDIF Export')
print('# Generated by nis2ldap (https://github.com/Caian/nis2ldap)')
print('')
print('version: 1')
print('')

groups = run(['ypcat', 'group'], stdout=PIPE, check=True).stdout
groups = groups.decode('utf8').split('\n')

for group in groups:
    group = group.strip()
    if group == '':
        continue
    group = group.split(':')
    assert group[1] == '!'
    print('dn: cn=%s,%s' % (group[0], dc))
    print('cn: %s' % group[0])
    print('gidnumber: %d' % int(group[2]))
    print('objectclass: posixGroup')
    print('objectclass: top')
    print('')

passwd = run(['ypcat', 'passwd'], stdout=PIPE, check=True).stdout
passwd = passwd.decode('utf8').split('\n')

entries = []

for user in passwd:
    user = user.strip()
    if user == '':
        continue
    user = user.split(':')
    uid = user[0]
    cn = user[4]
    cn = cn[0:cn.find(',')]
    if cn == '':
        print('Full name of %s:' % uid, end=' ')
        cn = input()
    entries.append('dn: uid=%s,%s' % (uid, dc))
    entries.append('uid: %s' % uid)
    entries.append('homedirectory: %s' % user[5])
    entries.append('loginshell: %s' % user[6])
    entries.append('objectclass: inetOrgPerson')
    entries.append('objectclass: posixAccount')
    entries.append('objectclass: top')
    entries.append('objectclass: shadowAccount')
    entries.append('uidnumber: %d' % int(user[2]))
    entries.append('gidnumber: %d' % int(user[3]))
    entries.append('userpassword: {CRYPT}%s' % user[1])
    entries.append('cn: %s' % cn)
    cn = cn.split()
    entries.append('givenname: %s' % cn[0])
    if len(cn) > 1:
        entries.append('sn: %s' % cn[-1])
    entries.append('')

print('\n'.join(entries))
